### ISSUE TITLE
Missing transform feedback functions

### ISSUE THREAD

**Issue by IcanDivideBy0** [grovesNL/glow#101]
Hello,
I'm about to start a PR to add transform feedback functions to glow.
Problem is that the OpenGL spec differs a bit from the webgl one:
```
OpenGL: multiple transfrom feedbacks created at once
void glGenTransformFeedbacks(GLsizei n, GLuint *ids);

WebGL: only one transfrom feedback created
gl.createTransformFeedback();
```
The OpenGL function generates multiple transform feedbacks while the WebGl generates only one at a time.

Which way do you think the glow abstraction should follow ?

I didn't dig a lot yet but I didn't see other differences in the specs for now.
Cheers

**Comment by IcanDivideBy0** [comment]
Here is what's currently missing

 webgl                           | opengl
---------------------------------|----------------
 createTransformFeedback         | glGenTransformFeedbacks
 deleteTransformFeedback         | glDeleteTransformFeedbacks
 isTransformFeedback             | glIsTransformFeedback
 bindTransformFeedback           | glBindTransformFeedback
 beginTransformFeedback          | glBeginTransformFeedback
 endTransformFeedback            | glEndTransformFeedback
 pauseTransformFeedback          | glPauseTransformFeedback
 resumeTransformFeedback         | glResumeTransformFeedback
 transformFeedbackVaryings       | glTransformFeedbackVaryings
 getTransformFeedbackVarying     | glGetTransformFeedbackVarying

Looks `glDeleteTransformFeedbacks` have the same problem.

Also, should transform feedbacks be tracked ?

**Comment by grovesNL** [comment]
Thanks! I think we can probably follow WebGL here and just create one at a time.

> Also, should transform feedbacks be tracked ?

Either sounds good to me, tracking them might make it slightly easier to port OpenGL code over. I guess it depends on how much users would reuse transform feedback handles internally (where `Copy` would probably be fine) vs. holding it in one or two structs (where `Clone` would probably be fine).

Basically we only need to track them it if we want to add `Copy + Eq + Hash + Ord + PartialEq + PartialOrd` to the handle we expose for `TransformFeedback`. If we don't track it then we can only have `Clone + Debug`. This is basically the difference between `UniformLocation` and the other associated types in https://github.com/grovesNL/glow/blob/59c017ccb513b7fb6f64acab7da3790a6483acc4/src/lib.rs#L75-L76
