### ISSUE TITLE
0.4.1 has breaking changes

### ISSUE THREAD

**Issue by 17cupsofcoffee** [grovesNL/glow#110]
0.4.1 is a patch release, but it includes the breaking changes from #66. This has caused Quicksilver and Tetra to stop building for new projects without a lock file.

Could this release be yanked?

Related issue: https://github.com/ryanisaacg/golem/issues/32

**Comment by grovesNL** [comment]
Oops, sorry about that! 0.4.1 is yanked now.

**Comment by 17cupsofcoffee** [comment]
Thank you for the quick fix :)
