### ISSUE TITLE
Modify PixelUnpackData::Slice(&'a [u8]) to PixelUnpackData::Slice(Option<&'a [u8]>)

### ISSUE THREAD

**Issue by TakWolf** [grovesNL/glow#113]
Modify:

https://github.com/grovesNL/glow/blob/49d66ae3f2228e9d82eadae584238229ad780e8b/src/lib.rs#L77-L80

to:
```rust
pub enum PixelUnpackData<'a> {
    BufferOffset(u32),
    Slice(Option<&'a [u8]>),
}
```
or
```rust
pub enum PixelUnpackData<'a> {
    BufferOffset(u32),
    Slice(&'a [u8]),
    Nullptr
}
```

in version 0.4.0, there is:

https://github.com/grovesNL/glow/blob/dee3af37c94e04dd16956d9fe899d147f5af310e/src/native.rs#L1525-L1549

but in 0.5.0, here is :

https://github.com/grovesNL/glow/blob/49d66ae3f2228e9d82eadae584238229ad780e8b/src/native.rs#L1508-L1535

```rust
        gl.TexSubImage2D(
            target,
            level,
            x_offset,
            y_offset,
            width,
            height,
            format,
            ty,
            match pixels {
                PixelUnpackData::BufferOffset(offset) => offset as *const std::ffi::c_void,
                PixelUnpackData::Slice(data) => data.as_ptr() as *const std::ffi::c_void,     // <--- no way to accept std::ptr::null()
            },
        );
```

**Comment by grovesNL** [comment]
Thanks for asking about this! Is there an issue with using `PixelUnpackData::BufferOffset(0)` for this use case?

For example, [in the spec](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glTexSubImage2D.xhtml):

> If a non-zero named buffer object is bound to the GL_PIXEL_UNPACK_BUFFER target (see glBindBuffer) while a texture image is specified, pixels is treated as a byte offset into the buffer object's data store.

so the idea was that an offset of 0 would be equivalent to `ptr::null`.

**Comment by TakWolf** [comment]
I get it, thank you!
