### ISSUE TITLE
Add glIsShader, glIsProgram, etc.

### ISSUE THREAD

**Issue by sebcrozet** [grovesNL/glow#116]
Hi! I am currently switching from custom WebGL bindings to `glow` for my [kiss3d](https://github.com/sebcrozet/kiss3d) project.

Unless I missed something, it appears that `glow` does not have test functions like [glIsShader](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glIsShader.xhtml), [glIsProgram](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glIsProgram.xhtml), [glIsBuffer](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glIsBuffer.xhtml), [glIsFramebuffer](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glIsFramebuffer.xhtml), [glIsRenderBuffer](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glIsRenderbuffer.xhtml), and [glIsTexture](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glIsTexture.xhtml). Is that something that could be added?

**Comment by grovesNL** [comment]
Hi! 👋 Yeah it would be great to add those.
