### ISSUE TITLE
Please release 0.6.1

### ISSUE THREAD

**Issue by tronical** [grovesNL/glow#128]
I'd be most grateful if a new release 0.6.1 (or 0.7?) could be made to crates.io as we'd like to publish a crate ourselves that requires 28e50672800f6f456cf8be53825001592d5a4eb3 and therefore we'd need a version of glow on crates.io that has the API.

Thanks in advance! :)

**Comment by grovesNL** [comment]
0.6.1 is published now: https://crates.io/crates/glow/0.6.1
