### ISSUE TITLE
Enable MSAA

### ISSUE THREAD

**Issue by Akzo-Andries** [grovesNL/glow#135]
I'm currently investigating cross-platform OpenGL solutions using Rust.
I've successfully used glow for this but now i'm stuck trying to enable MSAA.
Can you add an example how to enable this?

p.s. i'm not able to provide hints with the glow context but i'm able to enable features:
```
use crate::glow::HasContext;

context.blend_func(glow::SRC_ALPHA, glow::ONE_MINUS_SRC_ALPHA);
context.enable(glow::BLEND);
context.enable(glow::LINE_SMOOTH);
context.enable(glow::POLYGON_SMOOTH);
context.enable(glow::MULTISAMPLE);
```
Although this did not enable anti-aliasing in a simple OpenGL on windows implementation.

Please help.

**Comment by TannerRogalsky** [comment]
MSAA for the backbuffer is acquired through the window manager. In glutin, for example, it's specified through the `ContextBuilder`. https://docs.rs/glutin/0.25.1/glutin/struct.ContextBuilder.html#method.with_multisampling

There isn't currently a fully cross-platform abstraction this that works with the wasm32-unknown-unknown target. At least, not one that I'm aware of.

**Comment by Akzo-Andries** [comment]
Thank you for your response. I was not aware that this was part of the window context. For my Glutin implementation I have this now operational using your suggestion. I will now try to get this operational on different contexts as well.
