### ISSUE TITLE
Remove slotmap non-Copy workaround

### ISSUE THREAD

**Issue by orlp** [grovesNL/glow#142]
As soon as you're okay with bumping the minimum required Rust version to 1.49, you can remove the following workaround:

https://github.com/grovesNL/glow/blob/f4dcf90b4d683c61b2cc0f4fa00004bc814c5453/src/web_sys.rs#L59

`slotmap` 1.0 has removed the Copy restriction.

**Comment by grovesNL** [comment]
Thank you! We'll probably leave this for a little bit until 1.49 isn't as fresh
