### ISSUE TITLE
Dependency Issue

### ISSUE THREAD

**Issue by darjaallora** [grovesNL/glow#179]
cargo keeps returning an error and it could be me but I cannot get past it.

error: failed to select a version for the requirement `slotmap = "^0.3"`
candidate versions found which didn't match: 1.0.4, 0.4.1
location searched: crates.io index
required by package `glow v0.4.0`
    ... which is depended on by `bracket-terminal v0.8.0`
    ... which is depended on by `bracket-lib v0.8.0`
    ... which is depended on by `rltk v0.8.0`

It is probably something I'm doing wrong, but I'm new to rust and git and cannot tell.  Any workaround/fix is appreciated.  Thanks in advance.

**Comment by grovesNL** [comment]
Hi! :wave: Unfortunately it looks like slotmap 0.3 was removed in https://github.com/orlp/slotmap/issues/69, which breaks older versions of glow that used slotmap 0.3. There are a few possible fixes:

- I could backport slotmap updates into old version of glow
- a new version of slotmap 0.3 could be released
- bracket-terminal could update to a newer version of glow (increasing the version in https://github.com/amethyst/bracket-lib/blob/master/bracket-terminal/Cargo.toml#L25) and make a new release

**Comment by TannerRogalsky** [comment]
Hey! Welcome to Rust!

As @grovesNL said, it looks like an old version of glow lost one of it's dependencies. I've opened a PR to bracket-lib to update it which seems, to me, like the easiest way forward.

**Comment by darjaallora** [comment]
And ... we are fixed.  Thanks again everyone.
