### ISSUE TITLE
expose KHR_debug functionality on native

### ISSUE THREAD

**Issue by cormac-obrien** [grovesNL/glow#19]
Required for https://github.com/gfx-rs/gfx/issues/2826

I've already written a `native` implementation for the `KHR_debug` functions, but it adding it to `Context` would break the unified API since WebGL has no equivalent (I see [`WEBGL_debug`](https://www.khronos.org/registry/webgl/extensions/proposals/WEBGL_debug/) has been proposed but not implemented). How should we expose these functions?

For reference, the functions in question:

```
glDebugMessageControl
glDebugMessageInsert
glDebugMessageCallback
glGetDebugMessageLog
glGetPointerv
glPushDebugGroup
glPopDebugGroup
glObjectLabel
glGetObjectLabel
glObjectPtrLabel
glGetObjectPtrLabel
```

**Comment by grovesNL** [comment]
We can expose them here and just `panic` for WebGL. In gfx we can use `cfg` to avoid calling these for WebGL or add a `supports_debug_features` feature flag like we already do for some other features.

In the future, in glow we can probably expose some functions for feature checking (to move this functionality over from gfx). So then we could expose something like `supports_debug_features()` which would be hardcoded to `false` for WebGL.
