### ISSUE TITLE
Help converting cgmath `Matrix4<f32>` to `&[f32]`

### ISSUE THREAD

**Issue by junglie85** [grovesNL/glow#207]
Hey. Thanks for the great library. I'm using cgmath and trying to upload a `Matrix4<f32>` which is a struct of 4x `Vector4<f32>`s. This has an `Into` impl for `[[f32; 4]; 4]` but not `&[f32; 16]` which is what i think would be needed for the `uniform_matrix_4_f32_slice` method.

Do you have any suggestions on how I can upload this mat4 to GL?

**Comment by grovesNL** [comment]
Maybe some of the `bytemuck` functions might be able to help as I described a bit in #164, e.g. https://docs.rs/bytemuck/latest/bytemuck/fn.try_cast_slice.html

**Comment by junglie85** [comment]
Thanks, I didn't see that issue when I searched. I ended up using `slice::as_raw_parts` but I guess this is similar to what `bytemuck` does under the hood anyway:

```
let location = gl.get_uniform_location(program, name);
let data = (&array4x4(*matrix) as *const [[f32; 4]; 4]) as *const f32;
let raw = slice::from_raw_parts(data, 16);
gl.uniform_matrix_4_f32_slice(location.as_ref(), false, raw);
```
