### ISSUE TITLE
Please make contents of wrapper types public

### ISSUE THREAD

**Issue by surban** [grovesNL/glow#210]
Right now all handle wrappers (`NativeTexture`, `NativeShader`, etc.) have private contents. This hinders interop with other native APIs and libraries, which require the raw OpenGL handles.

Please make the contents of these types public, so that they can be created and consumed for interop with native code.

I.e. replace the texture definition with `pub struct NativeTexture(pub NonZeroU32);`.

**Comment by tronical** [comment]
I'm curious, are there any plans on making a new release of glow to crates.io that includes this change?
