### ISSUE TITLE
Add Zlib as a third licensing option

### ISSUE THREAD

**Issue by lunabunn** [grovesNL/glow#212]
With grovesNL's comment below, let's begin the process to relicense `glow` as `MIT OR Apache-2.0 OR Zlib`, adding the Zlib license as a third possible licensing option (for the original issue comment, please refer to the edit history).

# Rationale for Relicensing
The MIT license, while otherwise being a very permissive license, forces the burden of including the license text on all end users of the crate. Considering that this license text can (legally) be put literally anywhere, in practice this is often little more than a hassle. This requirement is especially bothersome for `glow` because it is a low-level bindings crate that most users interact with through other intermediary libraries.

On the other hand, the Zlib license only requires the license text to be included with **source distributions** of the crate. This grants a degree of protection amongst developers while freeing end users. In goodwill, the license also includes the following notice:
> If you use this software in a product, an acknowledgment in the product documentation would be appreciated but is not required.

For compatibility with the rest of the Rust ecosystem and downstream crates, which predominantly use `MIT OR Apache-2.0`, those two licenses should obviously remain as options. Therefore, `glow` should be relicensed as `MIT OR Apache-2.0 OR Zlib` to allow users to choose any of the MIT, Apache 2.0, or the Zlib licenses at their option.

# Contributor Checkoff
Being a change in license, this requires all contributors who have made copyrightable changes to the `glow` repository to agree.

Given below is a list of **all**  contributors to the `glow` project. If you agree to relicensing, please comment
> I license past and future contributions under the triple `MIT OR Apache-2.0 OR Zlib` license, allowing licensees to choose any one at their option.

Alternatively, you can also directly tick the checkbox next to your name. If you have any concerns, please comment those in this issue thread as well so that they can be discussed.

- [x] grovesNL
- [x] kvark
- [x] kyren
- [x] Lokathor
- [x] IcanDivideBy0
- [x] TannerRogalsky
- [x] coderedart
- [x] 17cupsofcoffee
- [x] segfault87
- [x] ryanisaacg
- [x] Frizi
- [x] cormac-obrien
- [x] memoryruins
- [x] iceiix
- [x] notdanilo
- [x] tronical
- [x] pum-purum-pum-pum
- [x] rspencer01
- [x] zicklag
- [x] cwfitzgerald
- [x] vtavernier
- [x] Gordon-F
- [x] aqrs
- [x] theypsilon
- [x] Hperigo
- [x] mrk-its
- [x] derezzedex
- [x] jaynus
- [x] DarkRyu550
- [x] SnoozeTime
- [x] Nazariglez
- [x] flukejones
- [x] rhelmot
- [x] Tazdevil971
- [x] prokopyl
- [x] mrDIMAS
- [x] Atul9
- [x] iamralpht
- [x] UE2020
- [x] katyo
- [x] morr0ne
- [x] surban
- [x] caiiiycuk
- [x] icefoxen
- [x] alvinhochun
\+
- [x] expenses (#216)
- [x] xyning (#217)

**Comment by grovesNL** [comment]
That sounds reasonable and I'd definitely be open to it, but we'd need all contributors to agree to it before we could do it.

Basically something like the wgpu re-licensing in https://github.com/gfx-rs/wgpu/issues/1473 which created a list of all code contributors and had everyone agree to it.

**Comment by lunabunn** [comment]
And a ping for everyone:
@kvark
@kyren
@Lokathor
@IcanDivideBy0
@TannerRogalsky
@coderedart
@17cupsofcoffee
@segfault87
@ryanisaacg
@Frizi
@cormac-obrien
@memoryruins
@iceiix
@notdanilo
@tronical
@pum-purum-pum-pum
@rspencer01
@zicklag
@cwfitzgerald
@vtavernier
@Gordon-F
@aqrs
@theypsilon
@Hperigo
@mrk-its
@derezzedex
@jaynus
@DarkRyu550
@SnoozeTime
@Nazariglez
@flukejones
@rhelmot
@Tazdevil971
@prokopyl
@mrDIMAS
@Atul9
@iamralpht
@UE2020
@katyo
@morr0ne
@surban
@caiiiycuk
@icefoxen
@alvinhochun

**Comment by morr0ne** [comment]
I license past and future contributions under the triple MIT OR Apache-2.0 OR Zlib license, allowing licensees to choose any one at their option.

**Comment by morr0ne** [comment]
Big fan of the Zlib license, hopefully this triple licensing becames standard

**Comment by ryanisaacg** [comment]
I license past and future contributions under the triple MIT OR Apache-2.0 OR Zlib license, allowing licensees to choose any one at their option.

**Comment by Atul9** [comment]
I license past and future contributions under the triple MIT OR Apache-2.0 OR Zlib license, allowing licensees to choose any one at their option.

**Comment by rhelmot** [comment]
I license past and future contributions under the triple MIT OR Apache-2.0 OR Zlib license, allowing licensees to choose any one at their option.

**Comment by Lokathor** [comment]
I license past and future contributions under the triple MIT OR Apache-2.0 OR Zlib license, allowing licensees to choose any one at their option.

**Comment by iamralpht** [comment]
I license past and future contributions under the triple MIT OR Apache-2.0 OR Zlib license, allowing licensees to choose any one at their option.

**Comment by cwfitzgerald** [comment]
I license past and future contributions under the triple MIT OR Apache-2.0 OR Zlib license, allowing licensees to choose any one at their option.

Glad to see it getting more adoption.

**Comment by kyren** [comment]
I license past and future contributions under the triple MIT OR Apache-2.0 OR Zlib license, allowing licensees to choose any one at their option.

**Comment by tronical** [comment]
I license past and future contributions under the triple MIT OR Apache-2.0 OR Zlib license, allowing licensees to choose any one at their option.

**Comment by flukejones** [comment]
I license past and future contributions under the triple MIT OR Apache-2.0 OR Zlib license, allowing licensees to choose any one at their option.

**Comment by coderedart** [comment]
I license past and future contributions under the triple MIT OR Apache-2.0 OR Zlib license, allowing licensees to choose any one at their option.

**Comment by segfault87** [comment]
I license past and future contributions under the triple MIT OR Apache-2.0 OR Zlib license, allowing licensees to choose any one at their option.

**Comment by 17cupsofcoffee** [comment]
I license past and future contributions under the triple MIT OR Apache-2.0 OR Zlib license, allowing licensees to choose any one at their option.

**Comment by rspencer01** [comment]
I license past and future contributions under the triple MIT OR Apache-2.0 OR Zlib license, allowing licensees to choose any one at their option.

**Comment by Gordon-F** [comment]
I license past and future contributions under the triple MIT OR Apache-2.0 OR Zlib license, allowing licensees to choose any one at their option.

**Comment by alvinhochun** [comment]
Fine for me.

I license past and future contributions under the triple MIT OR Apache-2.0 OR Zlib license, allowing licensees to choose any one at their option.

**Comment by vtavernier** [comment]
I license past and future contributions under the triple `MIT OR Apache-2.0 OR Zlib` license, allowing licensees to choose any one at their option.

**Comment by Nazariglez** [comment]
I license past and future contributions under the triple MIT OR Apache-2.0 OR Zlib license, allowing licensees to choose any one at their option.

**Comment by IcanDivideBy0** [comment]
I license past and future contributions under the triple MIT OR Apache-2.0 OR Zlib license, allowing licensees to choose any one at their option.

**Comment by theypsilon** [comment]
I license past and future contributions under the triple MIT OR Apache-2.0 OR Zlib license, allowing licensees to choose any one at their option.

**Comment by grovesNL** [comment]
I license past and future contributions under the triple MIT OR Apache-2.0 OR Zlib license, allowing licensees to choose any one at their option.

**Comment by cormac-obrien** [comment]
I license past and future contributions under the triple `MIT OR Apache-2.0 OR Zlib` license, allowing licensees to choose any one at their option.

**Comment by TannerRogalsky** [comment]
I license past and future contributions under the triple MIT OR Apache-2.0 OR Zlib license, allowing licensees to choose any one at their option.

**Comment by surban** [comment]
I license past and future contributions under the triple MIT OR Apache-2.0 OR Zlib license, allowing licensees to choose any one at their option.

**Comment by zicklag** [comment]
I license past and future contributions under the triple MIT OR Apache-2.0 OR Zlib license, allowing licensees to choose any one at their option.

**Comment by katyo** [comment]
I license past and future contributions under the triple MIT OR Apache-2.0 OR Zlib license, allowing licensees to choose any one at their option.

**Comment by memoryruins** [comment]
I license past and future contributions under the triple MIT OR Apache-2.0 OR Zlib license, allowing licensees to choose any one at their option.

**Comment by Tazdevil971** [comment]
I license past and future contributions under the triple `MIT OR Apache-2.0 OR Zlib` license, allowing licensees to choose any one at their option.

**Comment by Frizi** [comment]
I license past and future contributions under the triple MIT OR Apache-2.0 OR Zlib license, allowing licensees to choose any one at their option.

**Comment by aqrs** [comment]
No problem for me.

**Comment by lunabunn** [comment]
@aqrs Could you please comment
> I license past and future contributions under the triple MIT OR Apache-2.0 OR Zlib license, allowing licensees to choose any one at their option.
verbatim? Sorry for the technicality, but just to be on the safer side 😅

**Comment by aqrs** [comment]
I'm sorry

I license past and future contributions under the triple MIT OR Apache-2.0 OR Zlib license, allowing licensees to choose any one at their option.

**Comment by pum-purum-pum-pum** [comment]
I license past and future contributions under the triple MIT OR Apache-2.0 OR Zlib license, allowing licensees to choose any one at their option.

**Comment by UE2020** [comment]
I license past and future contributions under the triple MIT OR Apache-2.0 OR Zlib license, allowing licensees to choose any one at their option.

**Comment by expenses** [comment]
I license past and future contributions under the triple MIT OR Apache-2.0 OR Zlib license, allowing licensees to choose any one at their option.

**Comment by iceiix** [comment]
Thank you for this

I license past and future contributions under the triple MIT OR Apache-2.0 OR Zlib license, allowing licensees to choose any one at their option.

**Comment by mrDIMAS** [comment]
I license past and future contributions under the triple MIT OR Apache-2.0 OR Zlib license, allowing licensees to choose any one at their option.

**Comment by prokopyl** [comment]
I license past and future contributions under the triple MIT OR Apache-2.0 OR Zlib license, allowing licensees to choose any one at their option.

**Comment by SnoozeTime** [comment]
I license past and future contributions under the triple MIT OR Apache-2.0 OR Zlib license, allowing licensees to choose any one at their option.

**Comment by icefoxen** [comment]
I license past and future contributions under the triple MIT OR Apache-2.0 OR Zlib license, allowing licensees to choose any one at their option.

**Comment by xyning** [comment]
I license past and future contributions under the triple MIT OR Apache-2.0 OR Zlib license, allowing licensees to choose any one at their option.

**Comment by jaynus** [comment]
I license past and future contributions under the triple MIT OR Apache-2.0 OR Zlib license, allowing licensees to choose any one at their option.

**Comment by notdanilo** [comment]
I license past and future contributions under the triple MIT OR Apache-2.0 OR Zlib license, allowing licensees to choose any one at their option.

**Comment by mrk-its** [comment]
I license past and future contributions under the triple MIT OR Apache-2.0 OR Zlib license, allowing licensees to choose any one at their option.

**Comment by DarkRyu550** [comment]
I license past and future contributions under the triple MIT OR Apache-2.0 OR Zlib license, allowing licensees to choose any one at their option.

**Comment by caiiiycuk** [comment]
I license past and future contributions under the triple MIT OR Apache-2.0 OR Zlib license, allowing licensees to choose any one at their option.

**Comment by Hperigo** [comment]
I license past and future contributions under the triple MIT OR Apache-2.0 OR Zlib license, allowing licensees to choose any one at their option. 

:)

**Comment by grovesNL** [comment]
Thanks everyone! We'll include zlib from now on 🎉

**Comment by mrk-its** [comment]
I license past and future contributions under the triple MIT OR Apache-2.0
OR Zlib license, allowing licensees to choose any one at their option.

śr., 6 kwi 2022, 10:38 użytkownik Davide ***@***.***> napisał:
