### ISSUE TITLE
How to create a projection matrix

### ISSUE THREAD

**Issue by Misaka15535** [grovesNL/glow#215]
I asked others about the api above gl4, how to create a matrix, but not only the create matrix api above gl4 was not found. APIs below 4 were also not found.

According to the API design of glow. How can I create the projection matrix? For example, an orthographic projection matrix?

**Comment by xyning** [comment]
matrix operations are provided by math libraries instead of any graphics apis
check out crates like [`ultraviolet`](https://crates.io/crates/ultraviolet) or [`glam`](https://crates.io/crates/glam/)

**Comment by Misaka15535** [comment]
> 矩阵运算由数学库提供，而不是任何图形 api 检查板条箱，如[`ultraviolet`](https://crates.io/crates/ultraviolet)或[`glam`](https://crates.io/crates/glam/)

ok.
I'm wondering why There is no glOrtho API for glow.
Although operations are not in scope of glow. But this api is an api belonging to opengl.

I want to make a ui library. But I don't know how to convert the coordinates of opengl into pixels. Can you provide me with writing method, ideas or related information?

**Comment by Misaka15535** [comment]
Is there any math library that is convenient to use with glow?
