### ISSUE TITLE
called glDebugMessageCallback but it was not loaded.

### ISSUE THREAD

**Issue by aniketbiprojit** [grovesNL/glow#230]
Window Loader: SDL
```rs
let window = video_subsystem
    .window(title, width, height)
    .allow_highdpi()
    .opengl()
    .position_centered()
    .resizable()
    .build()
    .unwrap();
```

Glow debug callback:
```rs
unsafe {
    gl.enable(glow::DEBUG_OUTPUT);
    gl.enable(glow::DEBUG_OUTPUT_SYNCHRONOUS);

    if gl_attr.context_flags().has_debug() {
        println!("Debug mode");

        // call debug callback - errors here
        gl.debug_message_callback(|source, ty, id, severity, message| {
            println!(
                "OpenGL error: source: {:?}, type: {:?}, id: {:?}, severity: {:?}, message: {:?}",
                source, ty, id, severity, message
            );
        });
    } else {
        println!("Debug mode not enabled");
    }
}
```

Error:
```.log
4.1, Metal - 76.3

thread 'main' panicked at 'called glDebugMessageCallback but it was not loaded.'
```

**Comment by aniketbiprojit** [comment]
I realise now that KHR_Debug is not available for Apple. Is there a workaround? Else, we can close this issue.

**Comment by grovesNL** [comment]
You can use [`get_error`](https://github.com/grovesNL/glow/blob/f0045305b46e2f00248a27a4779ae86f16f0e374/src/lib.rs#L486) after GL function calls to check whether you ran into any issues along the way.

It's a bit expensive to do this so I'd recommend only calling it in debug mode or after a large batch of calls.

**Comment by aniketbiprojit** [comment]
I was going through this article: http://renderingpipeline.com/2013/09/simulating-khr_debug-on-macos-x/ but probably might need to run it in C++ before building any abstractions for rust. Or might just use a windows machine.
