### ISSUE TITLE
Creating texture from slice of bytes

### ISSUE THREAD

**Issue by jjant** [grovesNL/glow#232]
Hey there, I basically want to create a `Texture2D` to from a slice of bytes representing colors `&[u8]` (r, g, b, r, g, b, ...).

I'm currently using glium and I can do it with:
```rust
use glium::texture::{RawImage2d, SrgbTexture2d};
use glium::uniforms::{MagnifySamplerFilter, Sampler};
use glium::uniform;

let image = RawImage2d::from_raw_rgb(buffer.to_vec(), (128, 128));
let texture = SrgbTexture2d::new(display, image).unwrap();
let uniforms = uniform! {
    tex: Sampler::new(&texture).magnify_filter(MagnifySamplerFilter::Nearest)
};
```
Then I can use a `uniform sampler2D tex` in my shaders.

How can I achieve this in glow?

**Comment by grovesNL** [comment]
Hi @jjant :wave:! You'd do this using [`tex_image_2d`](https://docs.rs/glow/latest/glow/trait.HasContext.html#tymethod.tex_image_2d) using your bytes as the `pixels` parameter
