### ISSUE TITLE
Add setter for attribute `PointSize` of rasterized points

### ISSUE THREAD

**Issue by Nevsden** [grovesNL/glow#239]
Could a setter for the point size of rasterized points be implemented for the crate?
A setter is already available in the `GLFns` struct of the `gl46` module .

It could look like the following:

```rust
    unsafe fn point_size(&self, size: f32) {
        let gl = &self.raw;
        gl.PointSize(width);
    }
```

**Comment by grovesNL** [comment]
Hi! :wave: The preferred way to do this currently is by setting `gl_PointSize` in your shader instead if possible. You can switch point size mode with `GL_PROGRAM_POINT_SIZE` (`PROGRAM_POINT_SIZE` in glow). Would that work for your use case?

**Comment by Speykious** [comment]
I would personally like for this setter to be included. I'm not sure why the `PROGRAM_POINT_SIZE` method of doing things is preferrable (aside from being more generic), but I've used `glPointSize` at least for prototyping and debugging purposes. It saves me the trouble of having to modify a shader and potentially having to introduce a uniform just to set it to a different value between different draw calls.
