### ISSUE TITLE
Glutin v0.30.7

### ISSUE THREAD

**Issue by TeaSpillStudios** [grovesNL/glow#246]
Is there a way that the latest version (currently v0.30.7) could be used with Glow? I've tried simply using the documented method `from_loader_function` but I can't seem to get a pointer to the window. There is no function `get_proc_address` anymore on the `Window` type. I tried getting a raw window handle with `raw-window-handle` but I couldn't get it to cast to `*const _` as it's a non-primitive cast.

Is there a way that it could be used with the latest version of Glutin?

**Comment by notgull** [comment]
You can find an example of using `glow` with modern `glutin` and `winit` [here](https://github.com/notgull/piet-hardware/blob/main/crates/piet-glow/examples/util/setup_context.rs).

The example in this repo should probably be updated.

**Comment by TeaSpillStudios** [comment]
Thanks! I will take a look into this example and get my project working :+1:
