### ISSUE TITLE
`hello` example crashes

### ISSUE THREAD

**Issue by fenhl** [grovesNL/glow#252]
Apologies if this is the wrong place for this report. A user of my app (which uses [iced](https://docs.rs/iced)'s glow backend) is getting this error when attempting to run glow's `hello` example:

```
thread 'main' panicked at 'ERROR: 0:1: '' :  Version number not supported by OGL driver
WARNING: 0:2: extension GL_3DL_array_objects is being used but no proper #version pragrma was used
WARNING: 0:3: Only GLSL version > 110 allows postfix "F" or "f" for float
WARNING: 0:3: Only GLSL version > 110 allows postfix "F" or "f" for float
WARNING: 0:4: Only GLSL version > 110 allows postfix "F" or "f" for float
WARNING: 0:4: Only GLSL version > 110 allows postfix "F" or "f" for float
WARNING: 0:5: Only GLSL version > 110 allows postfix "F" or "f" for float
WARNING: 0:5: Only GLSL version > 110 allows postfix "F" or "f" for float
ERROR: 0:2: 'const 2-component vector of float' : cannot declare arrays of this qualifier
WARNING: 0:2: extension GL_3DL_array_objects is being used but no proper #version pragrma was used
ERROR: 0:2: 'const' :  non-matching types (using implicit conversion) for const initializer
ERROR: 0:7: 'out' :  supported in GLSL 1.30 or later
ERROR: 0:9: 'assign' :  cannot convert from 'float' to 'varying 2-component vector of float'

', examples\hello\src\main.rs:106:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

They have reported that their graphics drivers are up to date. If any further information is needed, I can contact them.

**Comment by notgull** [comment]
What operating system are they using?

**Comment by grovesNL** [comment]
Hi! :wave: Do you have any information about their graphics card/driver/which versions of OpenGL are supported by their hardwarwe? Are they able to run any other OpenGL programs?

**Comment by fenhl** [comment]
I only know that they're on Windows, waiting for a reply on the other info. Could you suggest another OpenGL program to test?

**Comment by fenhl** [comment]
They've reported the following:

* Windows 10
* Intel HD Graphics (CPU is Intel Core I5-660)
* driver version 8.15.10.2900 (2012-11-26)
* They're using an app called “OpenGL Extensions Viewer” which is reporting that they can use OpenGL up to 2.1 but also that their OpenGL version is “N/A”

**Comment by grovesNL** [comment]
OpenGL 2.1 would probably be too low for iced unfortunately
