### ISSUE TITLE
Is `debug_message_callback` sound?

### ISSUE THREAD

**Issue by epimeletes** [grovesNL/glow#256]
I could be confused, but look at this function from [native.rs](https://docs.rs/glow/0.12.3/src/glow/native.rs.html#2583-2601):

```rust
unsafe fn debug_message_callback<F>(&self, mut callback: F)
where
    F: FnMut(u32, u32, u32, u32, &str),
{
    let gl = &self.raw;

    if gl.DebugMessageCallback_is_loaded() {
        gl.DebugMessageCallback(
            Some(raw_debug_message_callback::<F>),
            &mut callback as *mut _ as *mut std::ffi::c_void,
        );
    } else {
        // Fallback to extension
        gl.DebugMessageCallbackKHR(
            Some(raw_debug_message_callback::<F>),
            &mut callback as *mut _ as *mut std::ffi::c_void,
        );
    }
}
```

The `callback` parameter is taken by value, a reference to `callback` is cast to a pointer and passed into `DebugMessageCallback`. When `debug_message_callback` returns, the lifetime of `callback` is over and the pointer that we passed is no longer valid. Am I missing something?

**Comment by grovesNL** [comment]
This could be documented better, but we're basically expecting the callback function to be valid for the duration of the GL context. The actual callback shouldn't be consumed in this case, e.g.:

```rust
fn main() {
    let callback = move || println!("test");
    print_fn_ptr(callback);
    print_fn_ptr(callback);
}

fn print_fn_ptr<F: FnMut()>(callback: F) {
    let fn_ptr = &callback as *const _ as *mut std::ffi::c_void;
    println!("{:?}", fn_ptr);
}
```

should print the same value for the function pointer.

**Comment by epimeletes** [comment]
Does Rust really guarantee this? My understanding was that there is no guarantee for stability of addresses (unless you use pinning).

**Comment by grovesNL** [comment]
Maybe that's a bad example. I'm not sure about the trait object lifetime guarantees here - my understanding was that it was ok as long as the closure outlives the GL context here.

Were you expecting to see the trait object itself passed as an argument, or the closure leaked somehow?

**Comment by grovesNL** [comment]
Looking at this some more, I didn't notice the temporary reference when we merged this originally. I think we need to change this to avoid the temporary trait object reference. We could probably store the debug callback on the native context and use that somehow.

**Comment by epimeletes** [comment]
Just to be clear I haven't run into any problems and your example does print the same address twice. But I think this is just a coincidence. The callback is moved into the function and it doesn't exist in the original scope anymore, it's just that in simple cases the compiler sees through this and reuses the same object.

Storing the callback inside the context is one solution. Another would be to take callback by reference, but then it would be the responsibility of the caller to keep it alive as long as the context is alive, which is perhaps not ideal.

**Comment by grovesNL** [comment]
Yeah my original example was wrong and I was accidentally comparing the address instead of the function pointers. The function pointer also happen to be the same but this was apparently a coincidence because of how rustc's codegen currently works, and not guaranteed.

We'll store the callback in the context as a raw pointer for now which seems to be the safest/most specified way at the moment until `Box` aliasing is fully defined.

**Comment by epimeletes** [comment]
Looks good, thanks for the fix!
