### ISSUE TITLE
vertex_attrib_pointer_f32 doesn't work without a VAO

### ISSUE THREAD

**Issue by implicit-invocation** [grovesNL/glow#264]
If I just bind the `ARRAY_BUFFER` and call `enable_vertex_attrib_array` + `vertex_attrib_pointer_f32` on attribute location, nothing will be drawn to the screen.  
Calling `enable_vertex_attrib_array` + `vertex_attrib_pointer_f32` after `bind_vertex_array` works normally.

**Comment by grovesNL** [comment]
Hi! :wave: If I understand correctly, this state is associated with the bound VAO, so this is expected.

**Comment by implicit-invocation** [comment]
iirc, using VAO is a way to cache the vertex_attrib_pointer_f32 calls, but using vertex_attrib_pointer_f32 directly should work too

**Comment by grovesNL** [comment]
Depending on the exact GL profile and version you're using then there may be a default VAO, e.g. from the Khronos OpenGL wiki (https://www.khronos.org/opengl/wiki/Vertex_Specification):

> The compatibility OpenGL profile makes VAO object 0 a default object. The core OpenGL profile makes VAO object 0 not an object at all. So if VAO 0 is bound in the core profile, you should not call any function that modifies VAO state. This includes binding the `GL_ELEMENT_ARRAY_BUFFER` with glBindBuffer.

You can also check the specification depending on the profile/versions you're targeting, e.g. in OpenGL when a non-zero VAO is required (https://registry.khronos.org/OpenGL-Refpages/gl4/html/glVertexAttribPointer.xhtml):

> GL_INVALID_OPERATION is generated if zero is bound to the GL_ARRAY_BUFFER buffer object binding point and the pointer argument is not NULL.

**Comment by implicit-invocation** [comment]
Okay, I will take a look at my targets to see whether it accepts zero VAO.
