### ISSUE TITLE
Next release on crates.io

### ISSUE THREAD

**Issue by surban** [grovesNL/glow#292]
Would it be possible to publish a new release to crates.io in the near future?

**Comment by grovesNL** [comment]
Yeah absolutely, I can try to make a release soon. Is there any specific functionality you're waiting on (just curious)?

**Comment by surban** [comment]
I am mainly interested in edfd08e. 

I think pushing this out in the near future is important given the role glow has in the ecosystem. Otherwise libraries building on top of glow will stop supporting `Send + Sync` for their data types.

**Comment by Drakulix** [comment]
Same thing here btw, smithay is blocked on Send+Sync for updating glow: https://github.com/Smithay/smithay/issues/1195

This also prevents us from updating our egui-glue code to the latest version.

**Comment by grovesNL** [comment]
Sorry for the delay! I'd like to fix #289 before making the next release but haven't gotten around to it yet. Anyone else can feel free to take a look if you'd like though. It's unlikely anyone will hit it in practice, but I don't want the callback to change much more across releases (especially in case we might have to change the public callback type for some reason).

**Comment by victoryforphil** [comment]
Any update now it seems #289 is completed?

**Comment by grovesNL** [comment]
Just released 0.14 https://crates.io/crates/glow
