### ISSUE TITLE
Typo in hello example, OpenGL 4.10 doesn't exist (yet)

### ISSUE THREAD

**Issue by vinhig** [grovesNL/glow#297]
There seems to be a typo in the hello example `main.rs`, when creating an OpenGL context the minor version referenced is "10", but alas, OpenGL 4.10 does not exist (yet).

https://github.com/grovesNL/glow/blob/c6e96041c024445ca5fba8cd749fad8d8752db7a/examples/hello/src/main.rs#L69

**Comment by grovesNL** [comment]
Ah yeah that should be 1, looks like it was change while upgrading glutin. Feel free to submit a PR if you'd like!

**Comment by grovesNL** [comment]
Fixed by #298
