### ISSUE TITLE
The example should be integrated into the main crate

### ISSUE THREAD

**Issue by Lokathor** [grovesNL/glow#39]
Instead of having the example be a sub-project that you have to CD into and run separately, it should simply be an example directly part of the `glow` crate.

Some examples are big enough to be their own sub-projects, but hello triangle isn't.

**Comment by grovesNL** [comment]
Yeah that sounds reasonable. I was thinking that we could have a few more complicated examples with shaders in separate files, so it might be nice to separate them.

**Comment by Bombfuse** [comment]
Are there anymore examples on how to use glow? I'm trying to figure out how to draw textures from data

**Comment by grovesNL** [comment]
@Bombfuse glow should align very closely to the regular GL API, except the function names are slightly different. So you should be able to follow a tutorial about drawing textures in GL with WebGL or OpenGL and apply it to glow without much trouble.

Please let me know if you have any difficulty with this and I'd be happy to help (we could talk on the #games-and-graphics channel on the [Rust Community Discord](https://bit.ly/rust-community), Riot, Zulip, or whatever works for you).

It would be good to add a few more examples to this repository in general though.

**Comment by Bombfuse** [comment]
Awesome sounds good to me! Thanks for the quick response

**Comment by grovesNL** [comment]
I think we'll keep them separate for now so we can show how the `sdl` and `glutin` features are used
