### ISSUE TITLE
Docs improvements tracker

### ISSUE THREAD

**Issue by Lokathor** [grovesNL/glow#40]
Here's stuff that's been used so far during the `learn-glow` book that we should put in docs for on the trait:

* [ ] clear_color
* [ ] clear

**Comment by iceiix** [comment]
@Lokathor Is the `learn-glow` book available anywhere (or is it being written privately)? Searched GitHub, only found this issue and #41. 

Looks like it used to be at https://github.com/rust-tutorials/learn-glow but this repository no longer exists? (found this cached page: https://webcache.googleusercontent.com/search?q=cache:MYU38SJCxgwJ:https://github.com/rust-tutorials/learn-glow/issues/3+&cd=1&hl=en&ct=clnk&gl=ca)

**Comment by Lokathor** [comment]
I didn't end up developing it at all. To avoid confusion about having a repo with no useful content i got rid of it.

If anyone wants to work on the project I can add them to the github org and get them set up to do it.
