### ISSUE TITLE
stdweb backend support

### ISSUE THREAD

**Issue by ryanisaacg** [grovesNL/glow#43]
I would like to contribute stdweb support at some point in the near-ish future. Before I get started, I just have a design question or two:

- Are you open to stdweb support?
- Should both web-sys and stdweb be behind features, or just have stdweb behind a feature?
- Should I try to reduce code duplication between web-sys and stdweb? The easiest way to create the stdweb backend would probably be to copy the web-sys backend and change the names and fix errors until the program typechecks, but that would mean that web changes have to be made twice

**Comment by grovesNL** [comment]
Oops, I missed the notification for this issue.

> Are you open to stdweb support?

Yeah, this sounds good to me! If stdweb eventually uses web-sys internally, then maybe this layer will disappear someday.

> Should both web-sys and stdweb be behind features, or just have stdweb behind a feature?

We could probably have both behind features. I don't have a strong preference how we setup the features, as long as the approach allows us to still target web-sys without building stdweb.

> Should I try to reduce code duplication between web-sys and stdweb?

It would be nice, but it's not necessary if there's no convenient path for this. Most functions will be 1-2 lines for now anyway. I guess we could eventually consider using a macro/code gen for some parts.

**Comment by grovesNL** [comment]
Fixed with #46 🎉
