### ISSUE TITLE
Context::from_loader_function should be marked unsafe

### ISSUE THREAD

**Issue by autumnontape** [grovesNL/glow#45]
The provided loader function is assumed to produce valid function pointers that behave as expected when called. If you pass in e.g. `|_| std::ptr::null()` it will trigger undefined behavior.

Also, if this is done, might it be possible to remove `unsafe` from some or all of the functions on `HasContext`?

**Comment by grovesNL** [comment]
Thanks for creating this issue! This sounds right – we should mark `from_loader_function` as `unsafe`.

I believe many (or all?) of the other `unsafe`s should remain though, or at least anywhere we're interacting with GPU resources. There is some good discussion in https://github.com/gfx-rs/gfx/issues/2453 about that issue.
