### ISSUE TITLE
Glium support?

### ISSUE THREAD

**Issue by YaLTeR** [grovesNL/glow#50]
Is it possible to somehow hook [glium](https://github.com/glium/glium) up to use glow as a backend? As far as I can tell, that would mean providing a [`glium::backend::Backend`](https://docs.rs/glium/0.26.0-alpha3/glium/backend/trait.Backend.html) implementation.

**Comment by grovesNL** [comment]
Thanks for asking about this! It would be really interesting to try to make this work to bring Glium to the web. I think it should be possible and would mostly just require mapping types/function names across.

I think the best way for Glium to use glow as a backend is to [replace the `gl_generator` build dependency with a `glow` dependency](https://github.com/glium/glium/blob/master/Cargo.toml#L50). Then anywhere gl types/functions are used, we just replace with the equivalent glow type/function name. If it's helpful, [there are some examples in the gfx repository which show how gfx moved to glow from gl_generator](https://github.com/gfx-rs/gfx/pull/2554/files#diff-52164d3e9f04573a8f0cca692bb45ad2R1167).

Afterwards it might still be necessary to implement that `Backend` type in Glium too. It looks like `Backend` is mostly to handle context creation and function loading. gfx also has a similar trait for handling context creation, so it wouldn't be too hard to implement this trait.
