### ISSUE TITLE
Rustify `get_attrib_location` API

### ISSUE THREAD

**Issue by icefoxen** [grovesNL/glow#54]
C-style, `glGetAttribLocation` returns a positive error on success or -1 on error.  Looks like `get_attrib_location()` does the same.  Can we make it return a `Result<u32,...>` or such instead?

I am totally awful at this, so I'm sorry if I'm mistaken about how this works.

**Comment by TannerRogalsky** [comment]
I think it's a good idea! `get_uniform_location` already follows the Rust pattern. If you'd like to give it a shot you can probably follow that example.

**Comment by grovesNL** [comment]
Fixed by #56
