### ISSUE TITLE
Avoid tracking `Self::UniformLocation` in slotmap

### ISSUE THREAD

**Issue by grovesNL** [grovesNL/glow#59]
We don't have a function like `delete_uniform_location` unlike all the other tracked resources. So we need to find a way to drop these values automatically.

Instead of the current approach we could either:
- use something like `Rc<WebGlUniformLocation>` for those backends and use ownership semantics and avoid storing in slotmap
- track something like `Rc<WebGlUniformLocation>` inside the slotmap and cleanup any `WebGlUniformLocation`s with a `strong_count` of `1` whenever `get_uniform_location` is called

**Comment by grovesNL** [comment]
Actually it looks like `WebGlUniformLocation` is `Clone`, so maybe we can just use that.

**Comment by theypsilon** [comment]
We just talked via email about this, I'll work on a PR addressing this bug.
