### ISSUE TITLE
glReadPixels support

### ISSUE THREAD

**Issue by ryanisaacg** [grovesNL/glow#62]
Is there a reason that glReadPixels doesn't appear to be supported? It looks to be in both desktop GL:

https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glReadPixels.xhtml

and WebGL:

https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/readPixels

I'm open to adding it if it would be in scope.

**Comment by grovesNL** [comment]
Nope there's no reason, please feel free to add it :+1:
