### ISSUE TITLE
glow/examples/hello fails to compile for window-glutin: error[E0599]: no variant or associated item named `EventsCleared`

### ISSUE THREAD

**Issue by iceiix** [grovesNL/glow#70]
Following the instructions at https://github.com/grovesNL/glow/tree/master/examples/hello to run with glutin fails with:

```
hello $ cargo run --features=window-glutin
   Compiling hello v0.1.0 (glow/examples/hello)
error[E0599]: no variant or associated item named `EventsCleared` found for type `winit::event::Event<_>` in the current scope
   --> examples/hello/src/main.rs:188:28
    |
188 |                     Event::EventsCleared => {
    |                            ^^^^^^^^^^^^^
    |                            |
    |                            variant or associated item not found in `winit::event::Event<_>`
    |                            help: there is a variant with a similar name: `MainEventsCleared`

error[E0599]: no variant or associated item named `RedrawRequested` found for type `winit::event::WindowEvent` in the current scope
   --> examples/hello/src/main.rs:198:38
    |
198 |                         WindowEvent::RedrawRequested => {
    |                                      ^^^^^^^^^^^^^^^ variant or associated item not found in `winit::event::WindowEvent`

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0599`.
error: could not compile `hello`.
```

rustc 1.40.0 on macOS 10.15.2. 

Currently hello/Cargo.toml is using glutin 0.22.0-alpha3 (on master, staging, and 0.4.0), new versions https://crates.io/crates/glutin/versions I tried with alpha4 and alpha5, and older versions alpha2 and alpha1, with the same result.

**Comment by iceiix** [comment]
Looks like this was an API change in winit: https://github.com/rust-windowing/winit/blob/d1c6506865c7bddbb5fb4d80a613e43ddc1370b5/CHANGELOG.md#0200-alpha-6-2020-01-03 says "EventsCleared has been renamed to MainEventsCleared."

I can update to the new events and them the example works, but confusing why the new incompatible version was automatically pulled in…

**Comment by grovesNL** [comment]
Thanks for reporting this issue!

You're right, we'll just need to update the example to use the new event enum variants and pin the winit version. The reason it updated automatically is described in https://github.com/rust-windowing/winit/issues/1362
