### ISSUE TITLE
Support for uniform arrays

### ISSUE THREAD

**Issue by IcanDivideBy0** [grovesNL/glow#85]
I'm currently building a skinning system with glow. When skinning a mesh, the common practice is to send all bones/joints transform to the vertex shader as a uniform array:

```glsl
#define MAX_JOINTS 100
uniform mat4 u_JointsTransforms[MAX_JOINTS];
```

This is usually done by a single call to `glUniformMatrix4fv`, by using the `count` parameter which allow to send an array of matrices (webgl allow for an arbitrary sized array and computes the `count` by itself). https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glUniform.xhtml

With the current design, it's not possible to achieve that, the only option left is to have multiple calls to `glow::Context::uniform_matrix_4_f32_slice`, once per matrix, which is pretty bad from a performance point of view.

What do you think is the best implementation for glow:
- adding the `count` parameter to when needed to all `uniform_` functions and removing the restriction on the given slice size (*breaking change*)
- creating new functions which allow for that use case, something like `uniform_xxx_slice_unchecked` (*makes the API obscure*)
- giving access to the raw context to let the user do whatever he wants by adding `#[cfg(target_arch = ...)]` all the way (*defeats the purpose of using glow*)

I think I prefer the first solution, it reflect more the OpenGL API, even if removing the slice size from the function declaration makes it a bit more unsafe, the function is already marked unsafe anyways.

**Comment by IcanDivideBy0** [comment]
Alos I'm using `nalgemra-glm` for math stuff, currently to send a matrix I have to write the following:
```rust
use std::convert::TryInto;
gl.uniform_matrix_4_f32_slice(
    loc,
    false,
    matrix.as_slice().try_into().unwrap_or(&[0.0; 16])
);
```
which could be simplified if removing the slice size from the parameter:
```rust
gl.uniform_matrix_4_f32_slice(loc, false, matrix.as_slice());
```

**Comment by grovesNL** [comment]
Could we remove the slice size (accepting `v: &[f32]` instead) and determine `count` for native GL like WebGL is doing?

i.e. `gl.uniform_matrix_4_f32_slice(loc, false, matrix.as_slice());` would pass `count` to native GL as `v.len() / 16`)

**Comment by IcanDivideBy0** [comment]
Seems good to me!
