### ISSUE TITLE
Consider committing the generated bindings

### ISSUE THREAD

**Issue by grovesNL** [grovesNL/glow#95]
Instead of running `gl_generator` as part of `build.rs` on native, we can probably have a crate that runs `gl_generator` and writes the generated bindings to a file that we commit. As far as I know, the generated bindings shouldn't vary by platform so this should be safe.

The biggest benefit is that we don't have to run the build step for `glow` anymore, which should help (non-incremental) compile times quite a bit.

For example, we do something similar in [`spirv_cross` with `bindgen`](https://github.com/grovesNL/spirv_cross/tree/master/bindings_generator).

**Comment by TannerRogalsky** [comment]
I don't love the idea of committing generated files but I have to admit that the custom build is pretty significant. This is maybe the most egregious possible example, though, as it's a fairly minimal project that has glow right at the top it's dependency tree. That seems like it's probably not typical.
![image](https://user-images.githubusercontent.com/654931/76368996-64c8f080-6308-11ea-90b1-4c77fd90121f.png)

In the context of a larger project it still takes a long time (second only to winapi) but it ends up blocking only a second with regards to it and the things that require it.
![image](https://user-images.githubusercontent.com/654931/76369193-2122b680-6309-11ea-92ca-d62ea4cc3757.png)

Incremental builds are already fast so I see this as mostly helping build systems. I dunno. I feel like I've sort of talked myself out this. That said, I'll never turn my nose up at someone making my builds faster haha.

**Comment by Lokathor** [comment]
Yeah the generated bindings don't depend in any way on the user's input to the crate, so there's no reason for `glow` to not generate the correct files once and then just commit that and save everyone downstream the build time.

**Comment by grovesNL** [comment]
Fixed by #111
